# Generated by Django 5.2 on 2025-04-26 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chambres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quantite', models.IntegerField()),
                ('date_acquisition', models.DateField()),
                ('etat', models.CharField(choices=[('neuf', 'Neuf'), ('bon', 'Bon état'), ('moyen', 'État moyen'), ('mauvais', 'Mauvais état')], max_length=20)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chambres.chambre')),
            ],
        ),
    ]
