# Generated by Django 5.2 on 2025-04-26 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeChambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('prix_par_nuit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('capacite', models.IntegerField()),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('occupee', 'Occupée'), ('maintenance', 'En maintenance'), ('nettoyage', 'En nettoyage')], max_length=20)),
                ('description', models.TextField()),
                ('etage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etages.etage')),
                ('type_chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chambres.typechambre')),
            ],
        ),
    ]
