# Generated by Django 5.2 on 2025-04-26 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chambres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_arrivee', models.DateTimeField()),
                ('date_depart', models.DateTimeField()),
                ('nombre_personnes', models.IntegerField()),
                ('statut', models.CharField(choices=[('confirmee', 'Confirmée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], max_length=20)),
                ('commentaires', models.TextField(blank=True)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chambres.chambre')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
