apiVersion: v1
kind: ConfigMap
metadata:
  name: hotel-management-config
  namespace: hotel-management
data:
  DJANGO_SETTINGS_MODULE: "hotel_management.settings"
  PYTHONUNBUFFERED: "1"
  PYTHONDONTWRITEBYTECODE: "1"
  LANGUAGE_CODE: "fr-fr"
  TIME_ZONE: "UTC"
  USE_I18N: "True"
  USE_L10N: "True"
  USE_TZ: "True"
  STATIC_URL: "/static/"
  MEDIA_URL: "/media/"
  LOGIN_URL: "users:login"
  LOGIN_REDIRECT_URL: "users:home"
  LOGOUT_REDIRECT_URL: "users:login"
  AUTH_USER_MODEL: "users.CustomUser"
  DEFAULT_AUTO_FIELD: "django.db.models.BigAutoField" 